[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
# via_ir disabled for fast test compilation (following Hedera docs)
via_ir = false
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.deploy]
# Deployment profile with via_ir for complex deployment scripts
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.hedera]
# Hedera testnet configuration
eth_rpc_url = "https://testnet.hashio.io/api"
chain_id = 296
gas_limit = 6000000
gas_price = 2000000000
optimizer = true
optimizer_runs = 200

[profile.hedera_mainnet]
# Hedera mainnet configuration
eth_rpc_url = "https://mainnet.hashio.io/api"
chain_id = 295
gas_limit = 6000000
gas_price = 2000000000
optimizer = true
optimizer_runs = 200

[profile.production]
# Production profile with maximum optimization (slower compilation)
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 10000
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false

[fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# RPC endpoints configuration (following Hedera best practices)
[rpc_endpoints]
hedera = "${HEDERA_RPC_URL}"
